//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>All Data Types</summary>
	[PublishedContentModel("allDataTypes")]
	public partial class AllDataTypes : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "allDataTypes";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public AllDataTypes(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<AllDataTypes, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Check Box
		///</summary>
		[ImplementPropertyType("checkBox")]
		public bool CheckBox
		{
			get { return this.GetPropertyValue<bool>("checkBox"); }
		}

		///<summary>
		/// Content Picker
		///</summary>
		[ImplementPropertyType("contentPicker")]
		public IPublishedContent ContentPicker
		{
			get { return this.GetPropertyValue<IPublishedContent>("contentPicker"); }
		}

		///<summary>
		/// Date Picker
		///</summary>
		[ImplementPropertyType("datePicker")]
		public DateTime DatePicker
		{
			get { return this.GetPropertyValue<DateTime>("datePicker"); }
		}

		///<summary>
		/// Drop Down
		///</summary>
		[ImplementPropertyType("dropDown")]
		public string DropDown
		{
			get { return this.GetPropertyValue<string>("dropDown"); }
		}

		///<summary>
		/// Drop Down Multiple
		///</summary>
		[ImplementPropertyType("dropDownMultiple")]
		public IEnumerable<string> DropDownMultiple
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("dropDownMultiple"); }
		}

		///<summary>
		/// Image Cropper
		///</summary>
		[ImplementPropertyType("imageCropper")]
		public Umbraco.Web.Models.ImageCropDataSet ImageCropper
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.ImageCropDataSet>("imageCropper"); }
		}

		///<summary>
		/// Label
		///</summary>
		[ImplementPropertyType("label")]
		public string Label
		{
			get { return this.GetPropertyValue<string>("label"); }
		}

		///<summary>
		/// List View Content
		///</summary>
		[ImplementPropertyType("listViewContent")]
		public object ListViewContent
		{
			get { return this.GetPropertyValue("listViewContent"); }
		}

		///<summary>
		/// List View Media
		///</summary>
		[ImplementPropertyType("listViewMedia")]
		public object ListViewMedia
		{
			get { return this.GetPropertyValue("listViewMedia"); }
		}

		///<summary>
		/// List View Members
		///</summary>
		[ImplementPropertyType("listViewMembers")]
		public object ListViewMembers
		{
			get { return this.GetPropertyValue("listViewMembers"); }
		}

		///<summary>
		/// Media Picker
		///</summary>
		[ImplementPropertyType("mediaPicker")]
		public IPublishedContent MediaPicker
		{
			get { return this.GetPropertyValue<IPublishedContent>("mediaPicker"); }
		}

		///<summary>
		/// Member Picker
		///</summary>
		[ImplementPropertyType("memberPicker")]
		public IPublishedContent MemberPicker
		{
			get { return this.GetPropertyValue<IPublishedContent>("memberPicker"); }
		}

		///<summary>
		/// Multiple Media Picker
		///</summary>
		[ImplementPropertyType("multipleMediaPicker")]
		public IEnumerable<IPublishedContent> MultipleMediaPicker
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("multipleMediaPicker"); }
		}

		///<summary>
		/// Numeric
		///</summary>
		[ImplementPropertyType("numeric")]
		public int Numeric
		{
			get { return this.GetPropertyValue<int>("numeric"); }
		}

		///<summary>
		/// Radio Box
		///</summary>
		[ImplementPropertyType("radioBox")]
		public int RadioBox
		{
			get { return this.GetPropertyValue<int>("radioBox"); }
		}

		///<summary>
		/// Related Links
		///</summary>
		[ImplementPropertyType("relatedLinks")]
		public Umbraco.Web.Models.RelatedLinks RelatedLinks
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.RelatedLinks>("relatedLinks"); }
		}

		///<summary>
		/// Rich Text Editor
		///</summary>
		[ImplementPropertyType("richTextEditor")]
		public IHtmlString RichTextEditor
		{
			get { return this.GetPropertyValue<IHtmlString>("richTextEditor"); }
		}

		///<summary>
		/// Tags
		///</summary>
		[ImplementPropertyType("tags")]
		public IEnumerable<string> Tags
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("tags"); }
		}

		///<summary>
		/// Text Area
		///</summary>
		[ImplementPropertyType("textArea")]
		public string TextArea
		{
			get { return this.GetPropertyValue<string>("textArea"); }
		}

		///<summary>
		/// Text String
		///</summary>
		[ImplementPropertyType("textString")]
		public string TextString
		{
			get { return this.GetPropertyValue<string>("textString"); }
		}

		///<summary>
		/// Upload
		///</summary>
		[ImplementPropertyType("upload")]
		public string Upload
		{
			get { return this.GetPropertyValue<string>("upload"); }
		}
	}
}
