//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>bike Model Page</summary>
	[PublishedContentModel("BikeModelPage")]
	public partial class BikeModelPage : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "BikeModelPage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public BikeModelPage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<BikeModelPage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Bike Image: Select image to be displayed on a card
		///</summary>
		[ImplementPropertyType("bikeImage")]
		public IPublishedContent BikeImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("bikeImage"); }
		}

		///<summary>
		/// Is Leading Model: Check if this is main model for submodels
		///</summary>
		[ImplementPropertyType("isLeadingModel")]
		public bool IsLeadingModel
		{
			get { return this.GetPropertyValue<bool>("isLeadingModel"); }
		}

		///<summary>
		/// Override From Label
		///</summary>
		[ImplementPropertyType("overrideFromLabel")]
		public string OverrideFromLabel
		{
			get { return this.GetPropertyValue<string>("overrideFromLabel"); }
		}

		///<summary>
		/// Override Specification Label
		///</summary>
		[ImplementPropertyType("overrideSpecificationLabel")]
		public string OverrideSpecificationLabel
		{
			get { return this.GetPropertyValue<string>("overrideSpecificationLabel"); }
		}

		///<summary>
		/// Property Default Test
		///</summary>
		[ImplementPropertyType("propertyDefaultTest")]
		public string PropertyDefaultTest
		{
			get { return this.GetPropertyValue<string>("propertyDefaultTest"); }
		}

		///<summary>
		/// Specification Content
		///</summary>
		[ImplementPropertyType("specificationContent")]
		public IHtmlString SpecificationContent
		{
			get { return this.GetPropertyValue<IHtmlString>("specificationContent"); }
		}

		///<summary>
		/// Sub Types
		///</summary>
		[ImplementPropertyType("subTypes")]
		public IEnumerable<IPublishedContent> SubTypes
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("subTypes"); }
		}
	}
}
