namespace DeployCmsData.UmbracoCms.Constants
{
    public enum CmsDataType
    {
        Label,
        Upload,
        Textarea,
        TextString,
        RichTextEditor,
        Numeric,
        Checkbox,
        CheckBoxList,
        DropDown,
        DatePicker,
        RadioBox,
        DropDownMultiple,
        FolderBrowser,
        ApprovedColor,
        DatePickerWithTime,
        ListViewContent,
        ListViewMedia,
        ListViewMembers,
        ContentPicker,
        MediaPicker2,
        MemberPicker,
        RelatedLinks,
        Tags,
        ImageCropper,
        MultipleMediaPicker,
        MultipleNodeTreePicker,
        SmallRichTextEditor,
        Accordian
    }
}
